clear
close all;

addpath(genpath("sub_functions"))
addpath("func_metrics")
addpath("methods")

fprintf("******* initium *******\n");

%% Selecting conditions
noise_conditions = { ...
    {0.1,   0.05,  0,     0,    0},     ... % g0.1 ps0.05 pt0 pd0
    {0.1,   0.1,   0,     0,    0},     ... % g0.1 ps0.05 pt0 pd0
    {0.1,   0,     0,     0,    0},     ... % g0.1 ps0 pt0
    {0,     0,     0.05,  0.5,  0},     ... % g0 ps0 pt0.05
    {0.05,  0.05,  0,     0,    0},     ... % g0.05 ps0.05 pt0
    {0.1,   0.05,  0,     0,    0},     ... % g0.1 ps0.05 pt0
    {0.05,  0,     0.05,  0.5,  0},     ... % g0.05 ps0 pt0.05
    {0.1,   0,     0.05,  0.5,  0},     ... % g0.1 ps0 pt0.05
    {0.05,  0.05,  0.05,  0.3,  0},     ... % g0.05 ps0.05 pt0.05
    {0.1,   0.05,  0.05,  0.3,  0},     ... % g0.1 ps0.05 pt0.05
    {0.05,  0.05,  0.05,  0.5,  0},     ... % g0.05 ps0.05 pt0.05
    {0.1,   0.05,  0.05,  0.5,  0},     ... % g0.1 ps0.05 pt0.05
    {0.05,  0.05,  0.05,  0.3,  0.001}, ... % g0.05 ps0.05 pt0.05 pd0.001
    {0.1,   0.05,  0.05,  0.3,  0.001}, ... % g0.1 ps0.05 pt0.05 pd0.001
};

% idc_noise_conditions = 1:size(noise_conditions, 2);
% idc_noise_conditions = [5:6, 11:14];
% idc_noise_conditions = 5:6;
idc_noise_conditions = 11:12;

images = {...
    "JasperRidge", ...
    "PaviaU", ...
    "Beltsville", ...
};

% idc_images = 1:numel(images);
idc_images = 1;


idx_exp = 0;
total_exp = length(idc_noise_conditions) * length(idc_images);


%% Setting common parameters
% rhos = {0.93, 0.95, 0.98};
rhos = {0.95};

% epsilon_rho = 0.01;

% % epsilon = epsilon_rho * sqrt(hsi.N * (1 - deg.sparse_rate));
% epsilon = rhos * deg.gaussian_sigma * sqrt(hsi.N * (1 - deg.sparse_rate));
% alpha = rhos * (0.5 * hsi.N * deg.sparse_rate);
% beta = rhos * hsi.N * (1 - deg.sparse_rate) ...
%     * deg.stripe_rate * deg.stripe_intensity / 2;

stopcri_idx = 5;
stopcri = 10 ^ -stopcri_idx;

maxiter = 20000;
% maxiter = 5;


%% Setting each methods info
% SSTV
methods_info(1) = struct( ...
    "name", "SSTV", ...
    "func", @(HSI_clean, HSI_noisy, params, deg) ...
        select_func_SSTV_for_denoising(HSI_clean, HSI_noisy, params, deg), ...
    "param_names", {{"maxiter", "stopcri", "rho_radius"}}, ...
    "params", {{maxiter, stopcri, rhos}}, ...
    "get_params_savetext", @(params, rho) ...
        sprintf("r%.2f_stop1e-%d", rho, stopcri_idx), ...
    "enable", false ...
);

% SSTV4
methods_info(end+1) = struct( ...
    "name", "SSTV4", ...
    "func", @(HSI_clean, HSI_noisy, params, deg)...
        select_func_SSTV4_for_denoising(HSI_clean, HSI_noisy, params, deg), ...
    "param_names", {{"maxiter", "stopcri", "rho_radius"}}, ...
    "params", {{maxiter, stopcri, rhos}}, ...
    "get_params_savetext", @(params, rho) ...
        sprintf("r%.2f_stop1e-%d", rho, stopcri_idx), ...
    "enable", false ...
);

% SSTV_Ono
methods_info(end+1) = struct( ...
    "name", "SSTV_Ono", ...
    "func", @(HSI_clean, HSI_noisy, params, deg)...
        func_SSTV_Ono_gst_for_denoising_by_NsPPDS(HSI_clean, HSI_noisy, params, deg), ...
    "param_names", {{"maxiter", "stopcri", "rho_radius"}}, ...
    "params", {{maxiter, stopcri, rhos}}, ...
    "get_params_savetext", @(params, rho) ...
        sprintf("r%.2f_stop1e-%d", rho, stopcri_idx), ...
    "enable", false ...
);

% RSSTV
methods_info(end+1) = struct( ...
    "name", "RSSTV", ...
    "func", @(HSI_clean, HSI_noisy, params, deg)...
        func_RSSTV_gst_for_denoising_by_NsPPDS(HSI_clean, HSI_noisy, params, deg), ...
    "param_names", {{"maxiter", "stopcri", "rho_radius"}}, ...
    "params", {{maxiter, stopcri, rhos}}, ...
    "get_params_savetext", @(params, rho) ...
        sprintf("r%.2f_stop1e-%d", rho, stopcri_idx), ...
    "enable", false ...
); 

% HSSTV_L1
% HSSTV_omega = {0.05};
HSSTV_omega = {0.01, 0.03, 0.05};

methods_info(end+1) = struct( ...
    "name", "HSSTV_L1", ...
    "func", @(HSI_clean, HSI_noisy, params, deg) ...
        select_func_HSSTV_for_denoising(HSI_clean, HSI_noisy, params, deg), ...
    "param_names", {{"L", "omega", "maxiter", "stopcri", "rho_radius"}}, ...
    "params", {{{"L1"}, HSSTV_omega, maxiter, stopcri, rhos}}, ...
    "get_params_savetext", @(params, rho) ...
        sprintf("o%.2f_r%.2f_stop1e-%d", params.omega, rho, stopcri_idx), ...
    "enable", false ...
);

% HSSTV_L12
methods_info(end+1) = struct( ...
    "name", "HSSTV_L12", ...
    "func", @(HSI_clean, HSI_noisy, params, deg) ...
        select_func_HSSTV_for_denoising(HSI_clean, HSI_noisy, params, deg), ...
    "param_names", {{"L", "omega", "maxiter", "stopcri", "rho_radius"}}, ...
    "params", {{{"L12"}, HSSTV_omega, maxiter, stopcri, rhos}}, ...
    "get_params_savetext", @(params, rho) ...
        sprintf("o%.2f_r%.2f_stop1e-%d", params.omega, rho, stopcri_idx), ...
    "enable", false ...
);

% HSSTV_L1_Ono
methods_info(end+1) = struct( ...
    "name", "HSSTV_L1_Ono", ...
    "func", @(HSI_clean, HSI_noisy, params, deg) ...
        func_HSSTV_Ono_gst_for_denoising_by_NsPPDS(HSI_clean, HSI_noisy, params, deg), ...
    "param_names", {{"L", "omega", "maxiter", "stopcri", "rho_radius"}}, ...
    "params", {{{"L1"}, HSSTV_omega, maxiter, stopcri, rhos}}, ...
    "get_params_savetext", @(params, rho) ...
        sprintf("o%.2f_r%.2f_stop1e-%d", params.omega, rho, stopcri_idx), ...
    "enable", false ...
);

% HSSTV4
methods_info(end+1) = struct( ...
    "name", "HSSTV4", ...
    "func", @(HSI_clean, HSI_noisy, params, deg) ...
        select_func_HSSTV4_for_denoising(HSI_clean, HSI_noisy, params, deg), ...
    "param_names", {{"omega", "maxiter", "stopcri", "rho_radius"}}, ...
    "params", {{HSSTV_omega, maxiter, stopcri, rhos}}, ...  
    "get_params_savetext", @(params, rho) ...
        sprintf("o%.2f_r%.2f_stop1e-%d", params.omega, rho, stopcri_idx), ...
    "enable", false ...
);

% l0l1HTV
l0l1HTV_stepsize_reduction = 0.999;
% l0l1HTV_stepsize_reduction = 0.9999;
% l0l1HTV_stepsize_reduction = 1;

l0l1HTV_L10ball_th = {0.02, 0.03};


methods_info(end+1) = struct( ...
    "name", "l0l1HTV", ...
    "func", @(HSI_clean, HSI_noisy, params, deg)...
        select_func_l0l1HTV_for_denoising(HSI_clean, HSI_noisy, params, deg), ...
    "param_names", {{"L10ball_th", "stepsize_reduction", ...
        "maxiter", "stopcri", "rho_radius"}}, ...
"params", {{l0l1HTV_L10ball_th, l0l1HTV_stepsize_reduction, ...
        maxiter, stopcri, rhos}}, ...
    "get_params_savetext", @(params, rho) ...
        sprintf("sr%.5g_th%.2f_r%.2f_maxiter%d", ...
            params.stepsize_reduction, params.L10ball_th, rho, maxiter), ...
    "enable", false ...
);

% LRTDTV
LRTDTV_tau = 1;
% LRTDTV_lambda = 100;
% LRTDTV_lambda_param = {10, 15, 20, 25, sqrt(hsi.n1*hsi.n2)};
% LRTDTV_lambda = cellfun(@(x) 100 * x / sqrt(hsi.n1*hsi.n2), LRTDTV_lambda_param);
LRTDTV_lambda_param = {10, 15, 20, 25, sqrt(100*100)};
LRTDTV_lambda = cellfun(@(x) 100 * x / sqrt(100*100), LRTDTV_lambda_param);
% LRTDTV_rank = {[51,51,10]};
% LRTDTV_rank = {[hsi.n1*0.8, hsi.n2*0.8, 10], [51, 51, 10]};
LRTDTV_rank = {[100*0.8, 100*0.8, 10], [51, 51, 10]};

methods_info(end+1) = struct( ...
    "name", "LRTDTV", ...
    "func", @(HSI_clean, HSI_noisy, params, deg) ...
        func_LRTDTV(HSI_clean, HSI_noisy, params, deg), ...
    "param_names", {{"tau", "lambda", "rank"}}, ...
    "params", {{LRTDTV_tau, LRTDTV_lambda, LRTDTV_rank}}, ...
    "get_params_savetext", @(params, ~) ...
        sprintf("l%.4g_r%d_stop1e-%d", params.lambda, params.rank(1), stopcri_idx), ...
    "enable", false ...
);

% TPTV
TPTV_Rank = {[7,7,5]};
TPTV_initial_rank = {2};
TPTV_maxIter = {50, 100};
% TPTV_lambda = 4e-3*sqrt(hsi.n1*hsi.n2);
TPTV_lambdas = {5e-4, 1e-4, 1e-3, 1e-2, 1.5e-2};

methods_info(end+1) = struct( ...
    "name", "TPTV", ...
    "func", @(HSI_clean, HSI_noisy, params, deg) ...
        func_TPTV_for_denoising(HSI_clean, HSI_noisy, params, deg), ...
    "param_names", {{"Rank", "initial_rank", "maxIter", "lambda"}}, ...
    "params", {{TPTV_Rank, TPTV_initial_rank, TPTV_maxIter, TPTV_lambdas}}, ...
    "get_params_savetext", @(params, ~) ...
        sprintf("maxiter%d_l%.4g", params.maxIter, params.lambda), ...
    "enable", false ...
);

% RISSTV
RISSTV_lambda = {0.01, 0.03, 0.05};

methods_info(end+1) = struct( ...
    "name", "RISSTV", ...
    "func", @(HSI_clean, HSI_noisy, params, deg) ...
        select_func_RISSTV_for_denoising(HSI_clean, HSI_noisy, params, deg), ...
    "param_names", {{"lambda", "maxiter", "stopcri", "rho_radius"}}, ...
    "params", {{RISSTV_lambda, maxiter, stopcri, rhos}}, ...
    "get_params_savetext", @(params, rho) ...
        sprintf("l%.2f_r%.2f_stop1e-%d", params.lambda, rho, stopcri_idx), ...
    "enable", false ...
);

% TdSSTV_L1
TdSSTV_w = {0, 0.2, 0.4, 0.6, 0.8, 1};

methods_info(end+1) = struct( ...
    "name", "TdSSTV_L1", ...
    "func", @(HSI_clean, HSI_noisy, params, deg) ...
        select_func_TdSSTV_for_denoising(HSI_clean, HSI_noisy, params, deg), ...
    "param_names", {{"L", "w", "maxiter", "stopcri", "rho_radius"}}, ...
    "params", {{{"L1"}, TdSSTV_w, maxiter, stopcri, rhos}}, ...
    "get_params_savetext", @(params, rho) ...
        sprintf("w%.2g_r%.2f_stop1e-%d", params.w, rho, stopcri_idx), ...
    "enable", false ...
);

% TdSSTV_L12
methods_info(end+1) = struct( ...
    "name", "TdSSTV_L12", ...
    "func", @(HSI_clean, HSI_noisy, params, deg) ...
        select_func_TdSSTV_for_denoising(HSI_clean, HSI_noisy, params, deg), ...
    "param_names", {{"L", "w", "maxiter", "stopcri", "rho_radius"}}, ...
    "params", {{{"L12"}, TdSSTV_w, maxiter, stopcri, rhos}}, ...
    "get_params_savetext", @(params, rho) ...
        sprintf("w%.2g_r%.2f_stop1e-%d", params.w, rho, stopcri_idx), ...
    "enable", false ...
);

% WeightedTdSSTV_L1
methods_info(end+1) = struct( ...
    "name", "WTdSSTV_L1", ...
    "func", @(HSI_clean, HSI_noisy, params, deg) ...
        func_WeightedTdSSTV_gst_for_denoising(HSI_clean, HSI_noisy, params, deg), ...
    "param_names", {{"L", "maxiter", "stopcri", "rho_radius"}}, ...
    "params", {{{"L1"}, maxiter, stopcri, rhos}}, ...
    "get_params_savetext", @(params, rho) ...
        sprintf("r%.2f_stop1e-%d", rho, stopcri_idx), ...
    "enable", false ...
);

methods_info(end+1) = struct( ...
    "name", "WTdSSTV_L12", ...
    "func", @(HSI_clean, HSI_noisy, params, deg) ...
        func_WeightedTdSSTV_gst_for_denoising(HSI_clean, HSI_noisy, params, deg), ...
    "param_names", {{"L", "maxiter", "stopcri", "rho_radius"}}, ...
    "params", {{{"L12"}, maxiter, stopcri, rhos}}, ...
    "get_params_savetext", @(params, rho) ...
        sprintf("r%.2f_stop1e-%d", rho, stopcri_idx), ...
    "enable", false ...
); 

% GTdSSTV_L1
GTdSSTV_sigma_x = {0.01, 0.1, 1};

methods_info(end+1) = struct( ...
    "name", "GTdSSTV_L1", ...
    "func", @(HSI_clean, HSI_noisy, params, deg) ...
        func_GraphTdSSTV_gst_for_denoising(HSI_clean, HSI_noisy, params, deg), ...
    "param_names", {{"L", "sigma_x", "maxiter", "stopcri", "rho_radius"}}, ...
    "params", {{{"L1"}, GTdSSTV_sigma_x, maxiter, stopcri, rhos}}, ...
    "get_params_savetext", @(params, rho) ...
        sprintf("x%.2g_r%.2f_stop1e-%d", params.sigma_x, rho, stopcri_idx), ...
    "enable", false ...
);

% GTdSSTV_L12
methods_info(end+1) = struct( ...
    "name", "GTdSSTV_L12", ...
    "func", @(HSI_clean, HSI_noisy, params, deg) ...
        func_GraphTdSSTV_gst_for_denoising(HSI_clean, HSI_noisy, params, deg), ...
    "param_names", {{"L", "sigma_x", "maxiter", "stopcri", "rho_radius"}}, ...
    "params", {{{"L12"}, GTdSSTV_sigma_x, maxiter, stopcri, rhos}}, ...
    "get_params_savetext", @(params, rho) ...
        sprintf("x%.2g_r%.2f_stop1e-%d", params.sigma_x, rho, stopcri_idx), ...
    "enable", false ...
);

% GASSTV
GASSTV_sigma_sp = [0.01, 0.1, 1];
GASSTV_sigma_s = [0.01, 1];
GASSTV_lambda1 = [0.01, 0.1, 1];
% GASSTV_lambda1 = [0.01];
GASSTV_lambda2 = [0.01, 0.1, 1];
% GASSTV_num_segments = [3, 5, 10];
GASSTV_num_segments = [3];
methods_info(end+1) = struct( ...
    "name", "GASSTV", ...
    "func", @(HSI_clean, HSI_noisy, params, deg) ...
        func_GASSTV_OraGuide_gst_for_denoising(HSI_clean, HSI_noisy, params, deg), ...
    "param_names", {{"L", "lambda1", "lambda2", "sigma_sp", "sigma_s", ...
        "num_segments", "maxiter", "stopcri", "rho_radius"}}, ...
    "params", {{{"L1"}, GASSTV_lambda1, GASSTV_lambda2, GASSTV_sigma_sp, GASSTV_sigma_s, ...
        GASSTV_num_segments, maxiter, stopcri, rhos}}, ...
    "get_params_savetext", @(params, rho) ...
        sprintf("l%.2g_%.2g_sp%.2g_s%.2g_ns%d_r%.2f_stop1e-%d", ...
        params.lambda1, params.lambda2, params.sigma_sp, params.sigma_s, ...
        params.num_segments, rho, stopcri_idx), ...
    "enable", false ...
);

% GASSTV
GASSTV_sigma_sp = [0.01, 0.1, 1];
GASSTV_sigma_s = [0.01, 1];
GASSTV_lambda1 = [0.01, 0.1, 1];
% GASSTV_lambda1 = [0.01];
GASSTV_lambda2 = [0.01, 0.1, 1];
% GASSTV_num_segments = [3, 5, 10];
GASSTV_num_segments = [3];
methods_info(end+1) = struct( ...
    "name", "GASSTV_noisy", ...
    "func", @(HSI_clean, HSI_noisy, params, deg) ...
        select_func_GASSTV_for_denoising(HSI_clean, HSI_noisy, params, deg), ...
    "param_names", {{"L", "lambda1", "lambda2", "sigma_sp", "sigma_s", ...
        "num_segments", "maxiter", "stopcri", "rho_radius"}}, ...
    "params", {{{"L1"}, GASSTV_lambda1, GASSTV_lambda2, GASSTV_sigma_sp, GASSTV_sigma_s, ...
        GASSTV_num_segments, maxiter, stopcri, rhos}}, ...
    "get_params_savetext", @(params, rho) ...
        sprintf("l%.2g_%.2g_sp%.2g_s%.2g_ns%d_r%.2f_stop1e-%d", ...
        params.lambda1, params.lambda2, params.sigma_sp, params.sigma_s, ...
        params.num_segments, rho, stopcri_idx), ...
    "enable", false ...
);

% GASSTV_Const
GASSTV_sigma_sp = [0.01, 0.05, 0.1];
GASSTV_sigma_l = [0.01, 0.05, 0.1];
GASSTV_lambda_rho_sp = [0.8, 0.9, 1, 1.1];
% GASSTV_lambda1 = [0.01];
GASSTV_lambda_rho_l = [0.8, 0.9, 1, 1.1];
% GASSTV_num_segments = [3, 5, 10];
GASSTV_num_segments = [3, 5];
methods_info(end+1) = struct( ...
    "name", "GASSTV_Const", ...
    "func", @(HSI_clean, HSI_noisy, params, deg) ...
        select_func_GASSTV_OraGuide_Const_for_denoising(HSI_clean, HSI_noisy, params, deg), ...
    "param_names", {{"sigma_sp", "sigma_l", "lambda_rho_sp", "lambda_rho_l", ...
        "num_segments", "maxiter", "stopcri", "rho_radius"}}, ...
    "params", {{GASSTV_sigma_sp, GASSTV_sigma_l, GASSTV_lambda_rho_sp, GASSTV_lambda_rho_l, ...
        GASSTV_num_segments, maxiter, stopcri, rhos}}, ...
    "get_params_savetext", @(params, rho) ...
        sprintf("lr%.2g_%.2g_sp%.2g_s%.2g_ns%d_r%.2f_stop1e-%d", ...
        params.lambda_rho_sp, params.lambda_rho_l, params.sigma_sp, params.sigma_l, ...
        params.num_segments, rho, stopcri_idx), ...
    "enable", true ...
);


methods_info = methods_info([methods_info.enable]); % removing false methods
num_methods = numel(methods_info);


%% Running Expt.
for idx_noise_condition = idc_noise_conditions
for idx_image = idc_images
%% Generating observation
deg.gaussian_sigma      = noise_conditions{idx_noise_condition}{1};
deg.sparse_rate         = noise_conditions{idx_noise_condition}{2};
deg.stripe_rate         = noise_conditions{idx_noise_condition}{3};
deg.stripe_intensity    = noise_conditions{idx_noise_condition}{4};
deg.deadline_rate       = noise_conditions{idx_noise_condition}{5};
image = images{idx_image};

[HSI_clean, hsi] = Load_HSI(image);
noise_seed = "default";
[HSI_noisy, deg] = Generate_obsv_for_denoising(HSI_clean, deg, noise_seed);

HSI_clean = single(HSI_clean);
HSI_noisy = single(HSI_noisy);

idx_exp = idx_exp + 1;

i_method = 0;


%% Running methods
for idx_method = 1:num_methods
name_method = methods_info(idx_method).name;
func_method = methods_info(idx_method).func;
params_name = methods_info(idx_method).param_names;
params_cell = methods_info(idx_method).params;


i_method = i_method + 1;


[params_comb, num_params_comb] = ParamsList2Comb(params_cell);

for idx_params_comb = 1:num_params_comb

params = struct();
for idx_params = 1:numel(params_name)
    % Assigning parameters to the structure
    params.(params_name{idx_params}) = params_comb{idx_params_comb}{idx_params};

    % If rho_radius exists, calculate epsilon, alpha, and beta
    if strcmp(params_name{idx_params}, "rho_radius")
        rho = params.rho_radius;
        % Calculating the rate except sparse noise and deadline noise
        rate_except_sd = 1 - deg.sparse_rate - 2*deg.deadline_rate + 2*deg.sparse_rate*deg.deadline_rate;
        params.epsilon = rho * deg.gaussian_sigma * sqrt(hsi.N * rate_except_sd);
        params.alpha = rho * (0.5 * hsi.N * (deg.sparse_rate - 2*deg.sparse_rate*deg.deadline_rate));
        params.beta = rho * hsi.N * rate_except_sd ...
            * deg.stripe_rate * deg.stripe_intensity / 2;
    end
end

if exist("rho", "var")
    name_params_savetext = methods_info(idx_method).get_params_savetext(params, rho);
else
    name_params_savetext = methods_info(idx_method).get_params_savetext(params, 0);
end



fprintf("\n~~~ SETTINGS ~~~\n");
fprintf("Method: %s\n", name_method);
fprintf("Image: %s Size: (%d, %d, %d)\n", image, hsi.n1, hsi.n2, hsi.n3);
fprintf("Gaussian sigma: %g\n", deg.gaussian_sigma);
fprintf("Sparse rate: %g\n", deg.sparse_rate);
fprintf("Stripe rate: %g\n", deg.stripe_rate);
fprintf("Stripe intensity: %g\n", deg.stripe_intensity);
fprintf("Deadline rate: %g\n", deg.deadline_rate);
fprintf("Parameter settings: %s\n", name_params_savetext)
fprintf("Methods: (%d/%d), Cases: (%d/%d), Params:(%d/%d)\n", ...
    i_method, num_methods, idx_exp, total_exp, idx_params_comb, num_params_comb);

[HSI_restored, removed_noise, other_result]...
    = func_method(HSI_clean, HSI_noisy, params, deg);


% Plotting results
val_mpsnr  = calc_MPSNR(HSI_restored, HSI_clean);
val_mssim  = calc_MSSIM(HSI_restored, HSI_clean);
val_sam    = calc_SAM(HSI_restored, HSI_clean);

fprintf("~~~ RESULTS ~~~\n");
fprintf("MPSNR: %#.4g\n", val_mpsnr);
fprintf("MSSIM: %#.4g\n", val_mssim);
fprintf("SAM  : %#.4g\n", val_sam);

[vals_psnr_per_band, vals_ssim_per_band] = calc_PSNR_SSIM_per_band(HSI_restored, HSI_clean);


% Saving each result
load("save_result_dir.mat", "save_result_dir");

save_folder_name = append(...
    save_result_dir, ...
    "denoising_", image, "/", ...
    "g", num2str(deg.gaussian_sigma), "_ps", num2str(deg.sparse_rate), ...
        "_pt", num2str(deg.stripe_rate), "_pd", num2str(deg.deadline_rate), "/", ...
    name_method, "/" ... 
);

mkdir(save_folder_name);

save(append(save_folder_name, name_params_savetext, ".mat"), ...
    "HSI_clean", "HSI_noisy", "hsi", "deg", "image", ...
    "HSI_restored", "removed_noise", ...
    "val_mpsnr", "val_mssim", "val_sam", ...
    "vals_psnr_per_band", "vals_ssim_per_band", ...
    "params", "other_result", ...
    "-v7.3", "-nocompression" ...
);

close all

end

end
end
end

fprintf("******* finis *******\n");
