% GASSTV_GLR_SW_NL_OG
params_GASSTV.sigma_sp = {"90", "med"};
params_GASSTV.sigma_l = {"90", "med"};
params_GASSTV.lambda_rho_sp = [0.9, 1, 1.1, 1.2];
params_GASSTV.patch_rad = [1,2];
params_GASSTV.k_nn = [10, 20];
params_GASSTV.lambda2 = [0.1, 1, 10];
% params_GASSTV.num_segments = [3, 5, 10];
params_GASSTV.num_segments = [5];
methods_info(end+1) = struct( ...
    "name", "GASSTV_GLR_SW_NL_OG", ...
    "func", @(HSI_clean, HSI_noisy, params, deg) ...
        select_func_GASSTV_GLR_SW_NL_OG_for_denoising(HSI_clean, HSI_noisy, params, deg), ...
    "param_names", {{"sigma_sp", "sigma_l", ...
        "lambda_rho_sp", "lambda2", ...
        "patch_rad", "k_nn", "num_segments", ...
        "maxiter", "stopcri", "rho_radius"}}, ...
    "params", {{params_GASSTV.sigma_sp, params_GASSTV.sigma_l, ...
        params_GASSTV.lambda_rho_sp, params_GASSTV.lambda2, ...
        params_GASSTV.patch_rad, params_GASSTV.k_nn, params_GASSTV.num_segments, ...
        maxiter, stopcri, rhos}}, ...
    "get_params_savetext", @(params) ...
        sprintf("lr%.2g_%.2g_sp%s_l%s_rad%d_knn%d_ns%d_r%g_stop1e-%d", ...
        params.lambda_rho_sp, params.lambda2, params.sigma_sp, params.sigma_l, ...
        params.patch_rad, params.k_nn, params.num_segments, ...
        params.rho_radius, stopcri_idx), ...
    "enable", true ...
);

% GASSTV_NL_OraG
params_GASSTV.sigma_sp = {"90", "med"};
params_GASSTV.sigma_l = {"90", "med"};
params_GASSTV.lambda_rho_sp = [0.9, 1, 1.1, 1.2];
params_GASSTV.patch_rad = [1,2];
params_GASSTV.k_nn = [10, 20];
params_GASSTV.lambda2 = [0.1, 1, 10];
params_GASSTV.num_segments = [3, 5, 10];
% params_GASSTV.num_segments = [5];
methods_info(1) = struct( ...
    "name", "GASSTV_NL_OraG", ...
    "func", @(HSI_clean, HSI_noisy, params, deg) ...
        select_func_GASSTV_NL_OraG_for_denoising(HSI_clean, HSI_noisy, params, deg), ...
    "param_names", {{"sigma_sp", "sigma_l", ...
        "lambda_rho_sp", "lambda2", ...
        "patch_rad", "k_nn", "num_segments", ...
        "maxiter", "stopcri", "rho_radius"}}, ...
    "params", {{params_GASSTV.sigma_sp, params_GASSTV.sigma_l, ...
        params_GASSTV.lambda_rho_sp, params_GASSTV.lambda2, ...
        params_GASSTV.patch_rad, params_GASSTV.k_nn, params_GASSTV.num_segments, ...
        maxiter, stopcri, rhos}}, ...
    "get_params_savetext", @(params) ...
        sprintf("lr%.2g_%.2g_sp%s_l%s_rad%d_knn%d_ns%d_r%g_stop1e-%d", ...
        params.lambda_rho_sp, params.lambda2, params.sigma_sp, params.sigma_l, ...
        params.patch_rad, params.k_nn, params.num_segments, ...
        params.rho_radius, stopcri_idx), ...
    "enable", false ...
);

% GASSTV_GTV_Oraguide_Const
params_GASSTV.sigma_sp = {"90", "med"};
params_GASSTV.sigma_l = {"90", "med"};
params_GASSTV.lambda_rho_sp = [0.9, 1, 1.1, 1.2];
% params_GASSTV.lambda1 = [0.01];
params_GASSTV.lambda_rho_l = [0.9, 1, 1.1, 1.2];
% params_GASSTV.num_segments = [3, 5, 10];
params_GASSTV.num_segments = [5];
methods_info(end+1) = struct( ...
    "name", "params_GASSTV.GTV_Oraguide_Const", ...
    "func", @(HSI_clean, HSI_noisy, params, deg) ...
        select_func_params_GASSTV.GTV_OraGuide_Const_for_denoising(HSI_clean, HSI_noisy, params, deg), ...
    "param_names", {{"sigma_sp", "sigma_l", "lambda_rho_sp", "lambda_rho_l", ...
        "num_segments", "maxiter", "stopcri", "rho_radius"}}, ...
    "params", {{params_GASSTV.sigma_sp, params_GASSTV.sigma_l, params_GASSTV.lambda_rho_sp, params_GASSTV.lambda_rho_l, ...
        params_GASSTV.num_segments, maxiter, stopcri, rhos}}, ...
    "get_params_savetext", @(params) ...
        sprintf("lr%.2g_%.2g_sp%s_s%s_ns%d_r%.2f_stop1e-%d", ...
        params.lambda_rho_sp, params.lambda_rho_l, params.sigma_sp, params.sigma_l, ...
        params.num_segments, params.rho_radius, stopcri_idx), ...
    "enable", false ...
);

% GASSTV_OraGuide
params_GASSTV.sigma_sp = [0.01, 0.1, 1];
params_GASSTV.sigma_s = [0.01, 1];
params_GASSTV.lambda1 = [0.01, 0.1, 1];
% params_GASSTV.lambda1 = [0.01];
params_GASSTV.lambda2 = [0.01, 0.1, 1];
% params_GASSTV.num_segments = [3, 5, 10];
params_GASSTV.num_segments = [3];
methods_info(end+1) = struct( ...
    "name", "GASSTV_Oraguide", ...
    "func", @(HSI_clean, HSI_noisy, params, deg) ...
        select_func_GASSTV_OraGuide_for_denoising(HSI_clean, HSI_noisy, params, deg), ...
    "param_names", {{"L", "lambda1", "lambda2", "sigma_sp", "sigma_s", ...
        "num_segments", "maxiter", "stopcri", "rho_radius"}}, ...
    "params", {{{"L1"}, params_GASSTV.lambda1, params_GASSTV.lambda2, params_GASSTV.sigma_sp, params_GASSTV.sigma_s, ...
        params_GASSTV.num_segments, maxiter, stopcri, rhos}}, ...
    "get_params_savetext", @(params) ...
        sprintf("l%.2g_%.2g_sp%.2g_s%.2g_ns%d_r%.2f_stop1e-%d", ...
        params.lambda1, params.lambda2, params.sigma_sp, params.sigma_s, ...
        params.num_segments, params.rho_radius, stopcri_idx), ...
    "enable", false ...
);

% GASSTV
params_GASSTV.sigma_sp = [0.01, 0.1, 1];
params_GASSTV.sigma_s = [0.01, 1];
params_GASSTV.lambda1 = [0.01, 0.1, 1];
% params_GASSTV.lambda1 = [0.01];
params_GASSTV.lambda2 = [0.01, 0.1, 1];
% params_GASSTV.num_segments = [3, 5, 10];
params_GASSTV.num_segments = [3];
methods_info(end+1) = struct( ...
    "name", "GASSTV", ...
    "func", @(HSI_clean, HSI_noisy, params, deg) ...
        select_func_params_GASSTV.for_denoising(HSI_clean, HSI_noisy, params, deg), ...
    "param_names", {{"L", "lambda1", "lambda2", "sigma_sp", "sigma_s", ...
        "num_segments", "maxiter", "stopcri", "rho_radius"}}, ...
    "params", {{{"L1"}, params_GASSTV.lambda1, params_GASSTV.lambda2, params_GASSTV.sigma_sp, params_GASSTV.sigma_s, ...
        params_GASSTV.num_segments, maxiter, stopcri, rhos}}, ...
    "get_params_savetext", @(params) ...
        sprintf("l%.2g_%.2g_sp%.2g_s%.2g_ns%d_r%.2f_stop1e-%d", ...
        params.lambda1, params.lambda2, params.sigma_sp, params.sigma_s, ...
        params.num_segments, params.rho_radius, stopcri_idx), ...
    "enable", false ...
);

% GASSTV_Oraguide_Const
params_GASSTV.sigma_sp = [0.01, 0.05, 0.1];
params_GASSTV.sigma_l = [0.01, 0.05, 0.1];
params_GASSTV.lambda_rho_sp = [0.9, 1, 1.1];
% params_GASSTV.lambda1 = [0.01];
params_GASSTV.lambda_rho_l = [0.9, 1, 1.1];
% params_GASSTV.num_segments = [3, 5, 10];
params_GASSTV.num_segments = [3, 5];
methods_info(end+1) = struct( ...
    "name", "GASSTV_Oraguide_Const", ...
    "func", @(HSI_clean, HSI_noisy, params, deg) ...
        select_func_GASSTV_OraGuide_Const_for_denoising(HSI_clean, HSI_noisy, params, deg), ...
    "param_names", {{"sigma_sp", "sigma_l", "lambda_rho_sp", "lambda_rho_l", ...
        "num_segments", "maxiter", "stopcri", "rho_radius"}}, ...
    "params", {{params_GASSTV.sigma_sp, params_GASSTV.sigma_l, params_GASSTV.lambda_rho_sp, params_GASSTV.lambda_rho_l, ...
        params_GASSTV.num_segments, maxiter, stopcri, rhos}}, ...
    "get_params_savetext", @(params) ...
        sprintf("lr%.2g_%.2g_sp%.2g_s%.2g_ns%d_r%.2f_stop1e-%d", ...
        params.lambda_rho_sp, params.lambda_rho_l, params.sigma_sp, params.sigma_l, ...
        params.num_segments, params.rho_radius, stopcri_idx), ...
    "enable", false ...
);