function result = Dvhbt_Neumann(z)
    result = cat(1, -z(1, :, :, 1), -z(2:end-1, :, :, 1) + z(1:end-2, :, :, 1), z(end-1, :, :, 1)) ...
        + cat(2, -z(:, 1, :, 2), -z(:, 2:end-1, :, 2) + z(:, 1:end-2, :, 2), z(:, end-1, :, 2)) ...
        + cat(3, -z(:, :, 1, 3), -z(:, :, 2:end-1, 3) + z(:, :, 1:end-2, 3), z(:, :, end-1, 3));
end